#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D _image_out;

layout(push_constant) uniform PushConstants {
	uvec2 image_size;
} _pc;

void main() {
	uvec2 gid = gl_GlobalInvocationID.xy;
	if (gid.x >= _pc.image_size.x || gid.y >= _pc.image_size.y) { return; }

	const vec4 out_color = vec4(vec2(_pc.image_size.xy), 1.0, 1.0);
	imageStore(_image_out, ivec2(gid), out_color);
}